tasks:
   - before: cp .bashrc ~/.bashrc && pip3 install -r requirements.txt
     command: . .bashrc && echo fAST for Deep Learning ... && ./run.sh datasets/github_java_10/4/1.java
   - command: . .bashrc && echo fAST for Parsing, Slicing, Diffing ... && cd datasets && ./download
   - command: . .bashrc && echo fAST for Bug Localisation ... && cd usr/bin && java -cp /workspace/demo-fast/usr/config:/workspace/demo-fast/usr/config/lic:/workspace/demo-fast/usr/lib/ConCodeSe-1.0.0.jar com.concodese.ConCodeSeJettyServerStarter SERVER_PORT=8081
